"""Synthetic lecture video generator.

Creates a fixed-camera "lecture" with a board, a lecturer, synthetic speech,
chalk sounds and strokes that appear on the board.  It is used by the test
suite (including the 60 s / 40 s / 20 s acceptance scenario of the design
document) and can be generated by users to try the application::

    cutsensei-cli demo lecture.mp4
"""

from __future__ import annotations

import math
import subprocess
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

import numpy as np

from .core import ffmpeg

AUDIO_SR = 48000


@dataclass
class Scene:
    kind: str          # "speech", "speech_writing", "writing", "idle", "walk"
    duration: float


@dataclass
class DemoSpec:
    scenes: List[Scene] = field(default_factory=lambda: [
        Scene("speech", 60.0), Scene("writing", 40.0), Scene("idle", 20.0)])
    width: int = 640
    height: int = 360
    fps: int = 30
    seed: int = 7

    @property
    def duration(self) -> float:
        return sum(s.duration for s in self.scenes)

    def scene_ranges(self) -> List[Tuple[str, float, float]]:
        out, t = [], 0.0
        for s in self.scenes:
            out.append((s.kind, t, t + s.duration))
            t += s.duration
        return out


# ----------------------------------------------------------------------------
# audio
# ----------------------------------------------------------------------------

_VOWELS = [  # (F1, F2, F3) in Hz
    (730, 1090, 2440), (270, 2290, 3010), (300, 870, 2240), (530, 1840, 2480),
    (570, 840, 2410), (440, 1020, 2240), (660, 1720, 2410),
]


def _speech(duration: float, rng: np.random.Generator, sr: int = AUDIO_SR) -> np.ndarray:
    """Additive synthesis of a speech-like signal (syllables with pitch)."""
    n = int(duration * sr)
    out = np.zeros(n, np.float32)
    t = 0.0
    while t < duration - 0.2:
        # a "word" of 2-5 syllables
        for _ in range(int(rng.integers(2, 6))):
            syl = float(rng.uniform(0.14, 0.26))
            if t + syl >= duration:
                break
            i0, i1 = int(t * sr), int((t + syl) * sr)
            m = i1 - i0
            tt = np.arange(m) / sr
            f0 = rng.uniform(105, 175) * (1 + 0.12 * np.sin(2 * np.pi * rng.uniform(1, 3) * tt))
            phase = 2 * np.pi * np.cumsum(f0) / sr
            f1, f2, f3 = _VOWELS[int(rng.integers(len(_VOWELS)))]
            sig = np.zeros(m)
            for k in range(1, 30):
                fk = k * f0
                amp = (np.exp(-((fk - f1) / 110) ** 2) + 0.6 * np.exp(-((fk - f2) / 160) ** 2)
                       + 0.3 * np.exp(-((fk - f3) / 220) ** 2) + 0.02)
                amp = np.where(fk < sr / 2 - 500, amp, 0) / k ** 0.5
                sig += amp * np.sin(k * phase)
            env = np.sin(np.pi * np.clip(tt / syl, 0, 1)) ** 0.6
            out[i0:i1] += (0.22 * env * sig / (np.abs(sig).max() + 1e-9)).astype(np.float32)
            # an unvoiced consonant after some syllables
            if rng.random() < 0.4:
                c0 = i1
                c1 = min(n, c0 + int(rng.uniform(0.03, 0.07) * sr))
                noise = rng.normal(0, 1, c1 - c0)
                noise = np.diff(np.concatenate([[0.0], noise]))
                out[c0:c1] += (0.02 * noise).astype(np.float32)
            t += syl + float(rng.uniform(0.02, 0.07))
        t += float(rng.uniform(0.12, 0.45))  # pause between words
    return out


def _chalk(duration: float, rng: np.random.Generator, sr: int = AUDIO_SR,
           rate: Tuple[float, float] = (3.0, 7.0)) -> np.ndarray:
    """Impulsive chalk taps and short scratches."""
    n = int(duration * sr)
    out = np.zeros(n, np.float32)
    t = float(rng.uniform(0.1, 0.4))
    while t < duration - 0.05:
        i0 = int(t * sr)
        length = int(rng.uniform(0.004, 0.015) * sr)
        burst = rng.normal(0, 1, length)
        burst = np.diff(np.concatenate([[0.0], burst]))  # high-pass
        burst *= np.exp(-np.arange(length) / (length / 4))
        out[i0:i0 + length] += (rng.uniform(0.08, 0.25) * burst[: n - i0]).astype(np.float32)
        t += float(rng.exponential(1.0 / rng.uniform(*rate)))
        if rng.random() < 0.05:
            t += float(rng.uniform(0.5, 1.5))  # thinking pause
    return out


def _room(n: int, rng: np.random.Generator, sr: int = AUDIO_SR) -> np.ndarray:
    white = rng.normal(0, 1, n)
    # cheap pink-ish noise
    pink = np.convolve(white, np.ones(8) / 8, mode="same")
    hum = 0.3 * np.sin(2 * np.pi * 50 * np.arange(n) / sr)
    return (0.0015 * (pink + hum)).astype(np.float32)


def synth_audio(spec: DemoSpec) -> np.ndarray:
    rng = np.random.default_rng(spec.seed)
    n = int(spec.duration * AUDIO_SR)
    audio = _room(n, rng)
    for kind, a, b in spec.scene_ranges():
        i0, i1 = int(a * AUDIO_SR), int(b * AUDIO_SR)
        if kind in ("speech", "speech_writing"):
            audio[i0:i1] += _speech(b - a, rng)[: i1 - i0]
        if kind in ("writing", "speech_writing"):
            audio[i0:i1] += _chalk(b - a, rng)[: i1 - i0]
        if kind == "walk":
            # footsteps: soft low thumps
            t = 0.3
            while t < b - a - 0.2:
                j = i0 + int(t * AUDIO_SR)
                m = int(0.05 * AUDIO_SR)
                thump = np.sin(2 * np.pi * 90 * np.arange(m) / AUDIO_SR) * \
                    np.exp(-np.arange(m) / (0.012 * AUDIO_SR))
                audio[j:j + m] += (0.03 * thump).astype(np.float32)
                t += 0.55
    return np.clip(audio, -1, 1)


# ----------------------------------------------------------------------------
# video
# ----------------------------------------------------------------------------

class _Board:
    def __init__(self, spec: DemoSpec, rng: np.random.Generator) -> None:
        w, h = spec.width, spec.height
        self.rng = rng
        self.x0, self.y0 = int(w * 0.08), int(h * 0.08)
        self.x1, self.y1 = int(w * 0.92), int(h * 0.72)
        base = np.zeros((h, w, 3), np.uint8)
        base[:] = (150, 150, 145)                          # wall (BGR)
        base[int(h * 0.72):] = (95, 105, 110)              # floor
        base[self.y0:self.y1, self.x0:self.x1] = (52, 78, 44)  # dark green board
        base[self.y1:self.y1 + 6, self.x0 - 4:self.x1 + 4] = (60, 60, 60)  # chalk tray
        self.base = base
        self.ink = np.zeros((h, w), np.uint8)
        # writing cursor (text lines)
        self.cx = self.x0 + 20
        self.cy = self.y0 + 30
        self.pen = np.array([self.cx, self.cy], float)

    def write_step(self, amount: float) -> Tuple[int, int]:
        """Advance the "handwriting" by ``amount`` pixels of stroke."""
        import cv2

        remaining = amount
        while remaining > 0:
            if self.rng.random() < 0.08:
                # new glyph: jump right
                self.cx += int(self.rng.integers(12, 22))
                if self.cx > self.x1 - 40:
                    self.cx = self.x0 + 20
                    self.cy += 34
                    if self.cy > self.y1 - 30:
                        self.cy = self.y0 + 30
                        self.ink[:] = 0  # board wiped (should not happen in tests)
                self.pen = np.array([self.cx + self.rng.uniform(0, 8),
                                     self.cy + self.rng.uniform(-10, 10)])
            step = self.rng.uniform(2, 5)
            angle = self.rng.uniform(0, 2 * np.pi)
            nxt = self.pen + step * np.array([np.cos(angle), np.sin(angle)])
            nxt[0] = np.clip(nxt[0], self.cx - 2, self.cx + 16)
            nxt[1] = np.clip(nxt[1], self.cy - 12, self.cy + 12)
            cv2.line(self.ink, tuple(int(v) for v in self.pen), tuple(int(v) for v in nxt), 1, 2)
            self.pen = nxt
            remaining -= step
        return int(self.pen[0]), int(self.pen[1])


def _draw_person(frame: np.ndarray, x: float, h: int, arm_to: Optional[Tuple[int, int]],
                 bob: float) -> None:
    import cv2

    body_top = int(h * 0.42 + bob)
    cx = int(x)
    cv2.rectangle(frame, (cx - 28, body_top), (cx + 28, h - 1), (70, 40, 40), -1)  # coat
    cv2.circle(frame, (cx, body_top - 22), 20, (150, 175, 215), -1)                 # head
    cv2.circle(frame, (cx, body_top - 30), 20, (40, 35, 30), -1, lineType=cv2.LINE_AA)
    cv2.circle(frame, (cx, body_top - 18), 17, (150, 175, 215), -1)
    if arm_to is not None:
        cv2.line(frame, (cx + 20, body_top + 12), arm_to, (70, 40, 40), 9)
        cv2.circle(frame, arm_to, 6, (150, 175, 215), -1)
    else:
        cv2.line(frame, (cx + 22, body_top + 12), (cx + 30, body_top + 80), (70, 40, 40), 9)


def generate_demo(path: str, spec: Optional[DemoSpec] = None,
                  crf: int = 26) -> DemoSpec:
    """Render the demo lecture to ``path`` (mp4, H.264 + AAC)."""
    import os
    import tempfile
    import wave

    spec = spec or DemoSpec()
    rng = np.random.default_rng(spec.seed)
    audio = synth_audio(spec)
    fd, wav_path = tempfile.mkstemp(suffix=".wav")
    os.close(fd)
    with wave.open(wav_path, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(AUDIO_SR)
        wf.writeframes((audio * 32767).astype("<i2").tobytes())

    w, h, fps = spec.width, spec.height, spec.fps
    cmd = [ffmpeg.find_ffmpeg(), "-hide_banner", "-loglevel", "error", "-y",
           "-f", "rawvideo", "-pix_fmt", "bgr24", "-s", f"{w}x{h}", "-r", str(fps),
           "-i", "pipe:0", "-i", wav_path, "-c:v", "libx264", "-preset", "veryfast",
           "-crf", str(crf), "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "128k",
           "-shortest", path]
    proc = ffmpeg.popen(cmd, stdin=subprocess.PIPE)
    board = _Board(spec, rng)
    # pre-computed sensor noise (cycled; cheaper than fresh noise per frame)
    noise_bank = [rng.normal(0, 2.0, (h, w, 3)).round().astype(np.int16) for _ in range(7)]
    person_x = w * 0.3
    target_x = person_x
    arm: Optional[Tuple[int, int]] = None
    try:
        total_frames = int(round(spec.duration * fps))
        ranges = spec.scene_ranges()
        for fi in range(total_frames):
            t = fi / fps
            kind = next((k for k, a, b in ranges if a <= t < b), ranges[-1][0])
            bob = 0.0
            arm = None
            if kind in ("writing", "speech_writing"):
                # stand next to the writing position and move the hand
                target_x = min(max(board.cx - 45, w * 0.12), w * 0.85)
                pen = board.write_step(rng.uniform(1.5, 4.0) if rng.random() > 0.05 else 0)
                arm = (pen[0], pen[1])
                bob = 1.5 * math.sin(t * 5)
            elif kind == "speech":
                target_x = w * 0.3 + 40 * math.sin(t * 0.3)
                bob = 2.0 * math.sin(t * 3)
                if (t % 7) < 2.0:
                    arm = (int(person_x + 60), int(h * 0.35 + 10 * math.sin(t * 4)))
            elif kind == "walk":
                target_x = w * 0.15 + (w * 0.7) * (0.5 + 0.5 * math.sin(t * 0.4))
                bob = 3.0 * abs(math.sin(t * 6))
            else:  # idle: stand still
                bob = 0.0
            person_x += (target_x - person_x) * 0.08
            frame = board.base.copy()
            frame[board.ink.astype(bool)] = (225, 228, 230)
            _draw_person(frame, person_x, h, arm, bob)
            noise = noise_bank[fi % len(noise_bank)]
            frame = np.clip(frame.astype(np.int16) + noise, 0, 255).astype(np.uint8)
            assert proc.stdin is not None
            proc.stdin.write(frame.tobytes())
        assert proc.stdin is not None
        proc.stdin.close()
        if proc.wait() != 0:
            raise RuntimeError("ffmpeg failed while encoding the demo video")
    finally:
        if proc.poll() is None:
            proc.kill()
        try:
            os.unlink(wav_path)
        except OSError:
            pass
    return spec


def board_region(spec: DemoSpec) -> List[float]:
    """Normalized board rectangle of the demo video."""
    return [0.08, 0.08, 0.84, 0.64]
